from os import getenv as os_getenv

FOOTER_TEXT = "2025 - by @behindsecurity"
TOKEN = os_getenv("TOKEN")
GAME_DATA_PATH = os_getenv("GAME_DATA_PATH")
BINGO_ADMIN_ROLE_ID = os_getenv("BINGO_ADMIN_ROLE_ID")
BUTTON_COOLDOWN = 5
DRAW_INTERVAL = 10
BINGO_THUMBNAIL_URL = ""
OWNER_ID = "1199395072983179356"
