TOKEN = "YOUR_BOT_TOKEN"
GAME_DATA_PATH = "./bingo_game_data.json"
BINGO_ADMIN_ROLE_ID = 1  # CHANGE ME (ROLE ID, INTEGER)
OWNER_ID = 1  # CHANGE ME (USER ID, INTEGER)
BINGO_THUMBNAIL_URL = ""
BUTTON_COOLDOWN = 5
DRAW_INTERVAL = 10
